### ISSUE TITLE
Bug on edit or upload Excel file

### ISSUE THREAD

**Issue by leolima** [tiefaces/TieFaces#15]
Hi, I would like to congratulate you for developing the component, it is very useful.

But i got the following error when:

1. Download the file clicking in "export result to excel" in url: http://showcase-tiefaces.rhcloud.com/showcase/sheet/WebSheetDataInput.xhtml

2. Upload the file downloaded on url: http://showcase-tiefaces.rhcloud.com/showcase/sheet/WebSheetUpload.xhtml

3. The component renderize the sheet with 1 more line

So, i suppose if I re-download this new uploaded file, and resend it. the component will renderize 2 more lines, got it?

Despite this, I really liked the component

**Comment by tiefaces** [comment]
Thank you leolima. Good catch. I will work on it.

**Comment by leolima** [comment]
maybe a start:
Get the WB in TieWebSheetBean and before updating the Inputstream remove the last line
```
XSSFSheet sheet = wb.getSheetAt(0);
sheet.shiftRows(this.getBodyRows().size(), this.getBodyRows().size(), -1);
```

**Comment by tiefaces** [comment]
Fixed in 1.0.7

**Comment by leolima** [comment]
Jason, sorry for this, but i had to modify 

this     

 		// repair last row if it's inserted in the configuration generation
 		Row lastrow = sheet.getRow(sheet.getLastRowNum());


for
    

 		// repair last row if it's inserted in the configuration generation
 		Row lastrow = sheet.getRow(sheet.getLastRowNum()-1);

**Comment by tiefaces** [comment]
Can you tell me why? As the getLastRowNum is 0 based. So sheet.getRow(sheet.getLastRowNum()) should return the last row in the sheet.
