### ISSUE TITLE
attr Rendered problem

### ISSUE THREAD

**Issue by leolima** [tiefaces/TieFaces#17]
The attribute defined on <tie:websheet rendered="false" ~ >

Does not work properly if we recover the value from managed beans. e.g:

![erro_tie_sheet](https://user-images.githubusercontent.com/1907885/28248522-3067de88-6a1c-11e7-817a-0b115bf3aa73.jpg)

**Comment by tiefaces** [comment]
fixed in 1.0.10. In rendered attribute doesn't work. Have to add an attribute into bean and use it instead. Will give the detail in showcase app.
