### ISSUE TITLE
translate labels in modal of remove line

### ISSUE THREAD

**Issue by renatofelixdev** [tiefaces/TieFaces#18]
![image](https://user-images.githubusercontent.com/23421105/29098852-fefc270a-7c77-11e7-8ca5-6c44d90f2bd1.png)

Hi Jason!

I would like to translate the all labels in remove line modal, but currently it is only possible to pass the contents the label of the modal body as a parameter to the component.

**Comment by tiefaces** [comment]
Hi Renato,

Good catch! I've add more attributes for this like below:

deleteRowConfirmHeader = "Confirmation"
deleteRowConfirmButtonYes = "Yes" 
deleteRowConfirmButtonNo = "No"

Please download version 1.0.9, let me if it still has issue.

Thanks
Jason Jiang

**Comment by tiefaces** [comment]
fixed in 1.0.9
