### ISSUE TITLE
possibility to define locale params outside template

### ISSUE THREAD

**Issue by chiarazambe-smeup** [tiefaces/TieFaces#26]
Hi Jason!

Actually locale params about date and numbers have to be specified in widgets for inputs. Moreover it's used default locale for outputs. It can be very useful to specify locale formats when setting WebSheetBean, so they can be dynamically injected by the client of the library.

**Comment by chiarazambe-smeup** [comment]
I did a PR for this issue. With this PR is possible to define the default locale and the default date pattern of the WebSheetBean:

this.setDefaultLocale(theDefaultLocaleIWant);     
this.setDefaultDatePattern(theDefaultPatternDateIWant);
InputStream stream = this.getClass().getClassLoader().getResourceAsStream("websheet/datacommentdemo.xlsx");
loadWebSheet(stream, context);

The WebSheetBean will render with this formats, if not different specified in the xlsx template.

**Comment by tiefaces** [comment]
Thank you very much.
